### ISSUE TITLE
Error running make for stm32mp1

### ISSUE THREAD

**Issue by kellyegan** [Seeed-Studio/seeed-linux-dtoverlays#10]
**Describe the bug**

When running make for stm32mp1 (Odyssey STM32MP157C)  get error "No such file"

**To Reproduce**
1. Steps to reproduce the behavior:
```
make all_stm32mp1 && sudo make install_stm32mp1
```

2. See errors in response below:
```
  DTC     overlays/stm32mp1/stm32mp1-seeed-spi5-overlay.dtbo
  DTC     overlays/stm32mp1/stm32mp1-MCP2517FD-can0-overlay.dtbo
  DTC     overlays/stm32mp1/stm32mp1-seeed-lcd-01-overlay.dtbo
  DTC     overlays/stm32mp1/stm32mp1-seeed-uart7-overlay.dtbo
  DTC     overlays/stm32mp1/stm32mp1-seeed-i2c4-overlay.dtbo
  DTC     overlays/stm32mp1/stm32mp1-seeed-ap6236-overlay.dtbo
  DTC     overlays/stm32mp1/stm32mp1-seeed-usart2-overlay.dtbo
scripts/Makefile.build:45: /home/debian/seeed-linux-dtverlays/modules/overlays/stm32mp1/config.txt/Makefile: No such file or directory
make[2]: *** No rule to make target '/home/debian/seeed-linux-dtverlays/modules/overlays/stm32mp1/config.txt/Makefile'.  Stop.
make[1]: *** [Makefile:1517: _module_/home/debian/seeed-linux-dtverlays/modules/overlays/stm32mp1/config.txt] Error 2
make: *** [Makefile:156: all_stm32mp1] Error 2
```

**Expected behavior**
 I would expect no errors on running make. Seems to lead to other errors when trying to use interfaces via python. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian (STM32MP157C image)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by turmary** [comment]
cd seeed-linux-dtoverlays
echo -ne > overlays/stm32mp1/config.txt
