### ISSUE TITLE
MCP2518FD Installation with the NANO Production module didn't work.

### ISSUE THREAD

**Issue by barovehicles** [Seeed-Studio/seeed-linux-dtoverlays#20]
When you use the installation procedure with the development board is all ok. But when you try to use with the production module the command: config-by-hardware.py don't work.
 
I'm using the carrier board B02 with the NANO Production module.

The problem is the Jetson-io library don't work with the production module.

How is possible to solve it?

**Comment by JakeSays** [comment]
@barovehicles I am only aware of the A02 and B01 carrier boards.

**Comment by JakeSays** [comment]
@barovehicles I just received a production module and now I see what you mean. It looks like it is in fact an issue with the jetson python scripts and not the driver.

**Comment by barovehicles** [comment]
Yes. The problem is the python script in the Jetson. that doesn't work with the production module.
The problem is understand how to do the procedure manually.

**Comment by is-qian** [comment]
Sorry for replying to you so late, is there any new progress on this issue?

**Comment by is-qian** [comment]
Sorry for replying to you so late, is there any new progress on this issue?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
