### ISSUE TITLE
CAN-HAT Driver fails to initialize on Jetson Nano production module

### ISSUE THREAD

**Issue by JakeSays** [Seeed-Studio/seeed-linux-dtoverlays#21]
After building and installing the mcp25xxfd driver for the can hat it fails to initialize.

Jetson module is the production one that has an EMMC module instead of the sdcard.
Using the latest L4T (v32.5.1)

dmesg output:
[    8.853886] spi_tegra114p: loading out-of-tree module taints kernel.
[    8.943685] tegra210-pinctrl 700008d4.pinmux: pin SPI1_CS1 PC4 already requested by 700008d4.pinmux; cannot claim for 7000d400.spi
[    8.943689] tegra210-pinctrl 700008d4.pinmux: pin-20 (7000d400.spi) status -22
[    8.943693] tegra210-pinctrl 700008d4.pinmux: could not request pin 20 (SPI1_CS1 PC4) from group spi1_cs1_pc4  on device 700008d4.pinmux
[    8.943696] spi-tegra114p 7000d400.spi: Error applying setting, reverse things back
[    8.943705] spi-tegra114p: probe of 7000d400.spi failed with error -22

**Comment by is-qian** [comment]
Sorry for replying to you so late, is there any new progress on this issue?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
