### ISSUE TITLE
hw timestamp missing

### ISSUE THREAD

**Issue by AleksandarFilipov** [Seeed-Studio/seeed-linux-dtoverlays#23]
**Describe the bug**
No hw timestamp provided when doing `candump -x -ta -H can0` 
Time `0` is always returned

**To Reproduce**

wire can1 and can0 by physically connecting wires to can_h and can_l
in _one_ terminal do:
`candump -x -ta -H can0`
in _anoter_ terminal do:
`cansend can1 123#123123`

**Expected behavior**
some increasing time is expected as output

Removing -H does report kernel time as expected `(1617269100.654171)  can0  RX - -  123   [3]  12 31 23`, but to get better precision `-H` is desired. And considering that the latest hat has a rtc onboard.

**Summary**
Thanks for providing and supporting a great can shield!

**Comment by is-qian** [comment]
Sorry for replying to you so late, is there any new progress on this issue?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
