### ISSUE TITLE
No ACK for CanFD frame reception when FD and BRS are both on

### ISSUE THREAD

**Issue by ChandlerLiu3** [Seeed-Studio/seeed-linux-dtoverlays#24]
**Describe the bug**

While the can0 is able to send out CanFD frames with BRS is on, it failed to receive any CanFD frames. The reason is the sample points of the arbitration and data fields are differently set.

**To Reproduce**
1. start up one CAN interface: 
     sudo ip link set can0 up type can bitrate 500000 dbitrate 2000000 restart-ms 1000 berr-reporting on fd on

- we can check the sample points via "ip link -details"

2. With a CAN bus tool, send a CAN-FD frame with BRS on
3. The bus tool complains there is no ACK is given by other node, here, it should be the CAN-HAT.

**Expected behavior**

ACK bit should be set.

**Screenshots**

** RPi **

Pi 3B

**Additional context**
Workaround: configure the sample point in the "ip link" command line.

  sudo ip link set can0 up type can bitrate 500000 sample-point 0.8 dbitrate 2000000 dsample-point 0.8 restart-ms 1000 berr-reporting on fd on

The driver shall make sure the sample points between the two fields are identical, although this might be an issue of the MCP25xxFD, which failed to sample the data field due to different sample point, and the CRC was wrong, and then the controller refuses to set the ACK bit.

**Comment by is-qian** [comment]
Sorry for replying to you so late, is there any new progress on this issue?
