### ISSUE TITLE
Can't find mipi_dsi_host

### ISSUE THREAD

**Issue by borongyuan** [Seeed-Studio/seeed-linux-dtoverlays#27]
你好，我接着 #26 进行尝试，在将linux-raspi更新至5.8后，scripts/reTerminal.sh可以顺利执行，不再出现编译错误。但是LCD屏幕仍然无法使用，启动时出现如下两行错误：
```
i2c_mipi_dsi 1-0045: Can't find mipi_dsi_host
i2c_mipi_dsi 1-0045: DSI device registration failed
```
我尝试了dtparam=i2c_arm=on，也没有用。请问下一步该如何排查？

**Comment by Pillar1989** [comment]
No，5.8 is not support

**Comment by borongyuan** [comment]
Well, I will try something else tomorrow.

**Comment by Pillar1989** [comment]
@borongyuan  if you have any news, we can reopen this issue.
