### ISSUE TITLE
Changing screen resolution on reTerminal

### ISSUE THREAD

**Issue by sondree** [Seeed-Studio/seeed-linux-dtoverlays#30]
Changing screen resolution in /boot/config.txt does nothing on the reTerminal. Is it possible to change the screen resolution? This is on raspberry pi OS, stock image.

**Comment by bigbearishappy** [comment]
Hello.The LCD on the reterminal can not change it's resolution.
you can confirm this by installing the arandr into you reterminal.
Configure->Screens->DSI-1->Resolution
But if you are using a hdmi screen.You change the hdmi screen's resolution with raspi-config.
