### ISSUE TITLE
reTerminal LCD does not work after latest RPi Bullseye Update (Kernel 5.15)

### ISSUE THREAD

**Issue by lakshanthad** [Seeed-Studio/seeed-linux-dtoverlays#40]
**Describe the bug**
After flashing the reTerminal with the latest Raspberry Pi OS Bullseye found [here](https://www.raspberrypi.com/software/operating-systems/), the LCD does not work anymore.

**To Reproduce**
1. Flash reTerminal with latest RPi OS Bullseye (Kernel 5.15) using RPi Imager
2. git clone --depth 1 https://github.com/Seeed-Studio/seeed-linux-dtoverlays
3. cd seeed-linux-dtoverlays
4. sudo ./scripts/reTerminal.sh
5. Reboot

**Expected behavior**
LCD worked with Kernal 5.10.x before

**Debug output**
The output of "dmesg | grep mipi" is as follows:

```sh

root@raspberrypi:~# dmesg | grep mipi
[    8.090686] i2c_mipi_dsi 1-0045: I2C read id: 0xc3
[    8.094604] [DSI]mipi_dsi_device:
[    8.315444] [DSI]mipi_dsi_probe:
[    8.899624] mipi_dsi fe700000.dsi.0: failed to attach dsi to host: -517
[    8.899791] [DSI]mipi_dsi_probe:
```

However. the LCD driver shows as loaded at 0x45:

```sh
root@raspberrypi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- UU -- -- -- -- -- --
20: UU -- -- -- -- -- -- -- -- UU -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- UU -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

Please help to fix this. Thank you.

Best Regards,
Lakshantha

**Comment by matsujirushi** [comment]
@lakshanthad 
Hi,
Currently, in testing.
https://github.com/matsujirushi/seeed-linux-dtoverlays/tree/reterminal/kernel5.15

1. reTerminal pre-install OS ... OK
2. Raspberry Pi OS 32-bit bullseye(2022/4/4) ... OK
3. Raspberry Pi OS 32-bit buster(2022/4/4) ... WIP

**Comment by lakshanthad** [comment]
Hello @matsujirushi,

Wonderful! That is great news! Looking forward to 64-bit testing also!

Best Regards,
Lakshanthad

**Comment by lakshanthad** [comment]
PR can be tracked here:
https://github.com/Seeed-Studio/seeed-linux-dtoverlays/pull/41

**Comment by nineisk** [comment]
Hi,

LCD worked for me.

[https://github.com/nineisk/seeed-linux-dtoverlays](url)

```
pi@reterminal:~ $ dmesg | grep DSI
[    5.652919] [DSI]i2c_md_init:
[    5.653168] [DSI]i2c_md_probe:start
[    5.660579] [DSI]mipi_dsi_device:
[    5.684693] [DSI]i2c_md_probe:finished.
[    5.749896] [DSI]mipi_dsi_probe:
[    6.273713] [DSI]mipi_dsi_probe:
[    6.515626] [DSI]panel_prepare:
[    6.571830] [DSI]ili9881d_prepare:
[    6.699863] [DSI]panel_enable:
[   10.620155] [DSI]panel_disable:
[   10.623447] [DSI]panel_unprepare:
[   10.679652] [DSI]panel_prepare:
[   10.735693] [DSI]ili9881d_prepare:
[   10.863702] [DSI]panel_enable:
[  610.674913] [DSI]panel_disable:
[  610.678012] [DSI]panel_unprepare:
[ 1204.750979] [DSI]panel_prepare:
[ 1204.809643] [DSI]ili9881d_prepare:
[ 1204.937674] [DSI]panel_enable:
pi@reterminal:~ $ uname -a
Linux reterminal 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
```

**Comment by matsujirushi** [comment]
Note:
https://forums.raspberrypi.com/viewtopic.php?p=1989017

**Comment by billstanden** [comment]
> PR can be tracked here:
> #41

This does not appear to resolve my issue on an reTerminal still on the older screen firmware version.

**Comment by lakshanthad** [comment]
LCD is working now according to this PR:
https://github.com/Seeed-Studio/seeed-linux-dtoverlays/pull/41

**Comment by maziarzamani** [comment]
Hi there. I have similar problems with Bullseye. Got the reTerminal last week and tried to install Bullseye 64-bit. 

```
pi@raspberrypi:~ $ dmesg | grep mipi
[    6.576060] i2c_mipi_dsi 1-0045: I2C read id: 0xc3
[    6.577774] [DSI]mipi_dsi_device:
[    6.608337] [DSI]mipi_dsi_probe:
[    7.248800] mipi_dsi fe700000.dsi.0: failed to attach dsi to host: -517
[    7.266310] [DSI]mipi_dsi_probe:
```
