### ISSUE TITLE
ReTerminal setup script fails on RPi OS Lite due to missing folders

### ISSUE THREAD

**Issue by fake-name** [Seeed-Studio/seeed-linux-dtoverlays#48]
I'm trying to run `scripts/reTerminal.sh` on a fresh lite rpi os install. 

The script fails due to assuming a number of directories exist, presumably since they do exist on the non-lite os.

Missing folders:

 - `/usr/share/plymouth/themes/`
 - `/usr/share/X11/xorg.conf.d/`
 - `/etc/plymouth/`

Creating these directories lets the installer finish successfully. `mkdir -p <folders>` should probably be run prior to blindly copying files into them: https://github.com/Seeed-Studio/seeed-linux-dtoverlays/blob/master/scripts/reTerminal.sh#L281-L283

**Comment by bigbearishappy** [comment]
Already fixed [here](https://github.com/Seeed-Studio/seeed-linux-dtoverlays/pull/44)
