### ISSUE TITLE
is it possible to obtain both roll pitch yaw angle from the accelerometer ?

### ISSUE THREAD

**Issue by sunnykwok97** [Seeed-Studio/seeed-linux-dtoverlays#49]
hi

I have tried to obtain both roll pitch yaw angles from the accelerometer. I have successfully gotten the roll pitch angle by following the algorithm, but the yaw angle (z-axis) is not correct. Should I buy an extra IMU for the task? Thank you 
![603423074](https://user-images.githubusercontent.com/109644432/179897293-53a64ef6-2c0b-4add-a47e-49dc7392a7aa.jpg)

**Comment by bigbearishappy** [comment]
Usually, if we want to get the accurate data of roll/pitch/yaw angls.it's better to get a IMU.
