### ISSUE TITLE
Build Error when building STM32MP1 overlays

### ISSUE THREAD

**Issue by Whitt83** [Seeed-Studio/seeed-linux-dtoverlays#5]
Following the instructions at https://wiki.seeedstudio.com/ODYSSEY-STM32MP157C/#set-to-the-gpio-mode -- 

1. Successful.
2. Clone successful, cd successful, but the make all_stm32mp1 fails with the attached log.

[seeed-stm32mp1_build_error.txt](https://github.com/Seeed-Studio/seeed-linux-dtoverlays/files/4875349/seeed-stm32mp1_build_error.txt)

**Comment by Hansen0314** [comment]
Hi @Whitt83 :
  we have been updating the wiki. you can use this cmd
`export CUSTOM_MOD_FILTER_OUT="jtsn-wm8960"` before using `make all_stm32mp1` .
like this
`
export CUSTOM_MOD_FILTER_OUT="jtsn-wm8960"
make all_stm32mp1 && sudo make install_stm32mp1
`
