### ISSUE TITLE
Guidelines for contributing seem to be missing

### ISSUE THREAD

**Issue by Paraphraser** [Seeed-Studio/seeed-linux-dtoverlays#51]
I was preparing a Pull Request wanted to read the guidelines so I clicked on `CONTRIBUTING.md`.

On that page, the "How to contribute guideline" link refers to:

* [https://github.com/Seeed-Studio/seeed-linux-dtoverlays/wiki/How_to_contribute](https://github.com/Seeed-Studio/seeed-linux-dtoverlays/wiki/How_to_contribute).

Clicking that link returns to [https://github.com/Seeed-Studio/seeed-linux-dtoverlays](https://github.com/Seeed-Studio/seeed-linux-dtoverlays).

It looks to me like the Wiki does not exist.

**Comment by bigbearishappy** [comment]
Yes, it seems that the previous maintainer forget to finish this work.
But after I check the project.There is nothing special that we need to tell the new contributor.Just make your change and create the PR is OK.
If we need to tell more about contributing in the future, we will finish it.
Thank you for your reminder.
