### ISSUE TITLE
reTerminal: Problems with LCD touch screen after installing Raspbian 64-bit Bullseye

### ISSUE THREAD

**Issue by maziarzamani** [Seeed-Studio/seeed-linux-dtoverlays#55]
**Describe the bug**
When reTerminal Drivers are installed and system is booted, is seems like Raspbian hits an infinite reboot condition. After 5-10 minutes it finally boots up and the system appears on the LCD screen. I am not sure if this I an LCD screen problem or something else, but it is not behaving as it should. When it boots, the touch screen is not working correctly either.

**UPDATE 3/10-22:**
I tried to reinstall the system several times, now it seems to be booting ok, however the touch screen is completely messed up. There is a huge displacement.

**UPDATE 4/10-22:**
I flashed the FW on the STM controller, however the touch interface is still messed up.

**To Reproduce**
1. Follow the guide here https://wiki.seeedstudio.com/reTerminal/
2. Replace Raspbian OS32-bit with 64-bit. 
3. Flash.

**Expected behavior**
That the system boots properly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian 64-bit

**Additional context**

```
DKMS: install completed.
  DTC     overlays/rpi/reTerminal-overlay.dtbo
overlays/rpi/reTerminal-overlay.dts:23.15-33.5: Warning (avoid_unnecessary_addr_size): /fragment@1/__overlay__: unnecessary #address-cells/#size-cells without "ranges" or child "reg" property
'overlays/rpi/reTerminal-overlay.dtbo' -> '/boot/overlays/reTerminal.dtbo'
  DTC     overlays/rpi/reTerminal-bridge-overlay.dtbo
'overlays/rpi/reTerminal-bridge-overlay.dtbo' -> '/boot/overlays/reTerminal-bridge.dtbo'
'/home/pi/Downloads/seeed-linux-dtoverlays/extras/reTerminal/resources/plymouth/seeed/' -> '/usr/share/plymouth/themes/seeed'
'/home/pi/Downloads/seeed-linux-dtoverlays/extras/reTerminal/resources/plymouth/seeed/seeed.plymouth' -> '/usr/share/plymouth/themes/seeed/seeed.plymouth'
'/home/pi/Downloads/seeed-linux-dtoverlays/extras/reTerminal/resources/plymouth/seeed/seeed.script' -> '/usr/share/plymouth/themes/seeed/seeed.script'
'/home/pi/Downloads/seeed-linux-dtoverlays/extras/reTerminal/resources/plymouth/seeed/splash.png' -> '/usr/share/plymouth/themes/seeed/splash.png'
'/home/pi/Downloads/seeed-linux-dtoverlays/extras/reTerminal/resources/plymouth/seeed/splash_v.png' -> '/usr/share/plymouth/themes/seeed/splash_v.png'
'/home/pi/Downloads/seeed-linux-dtoverlays/extras/reTerminal/resources/10-disp.conf' -> '/usr/share/X11/xorg.conf.d/10-disp.conf'
'/home/pi/Downloads/seeed-linux-dtoverlays/extras/reTerminal/resources/plymouth/plymouthd.conf' -> '/etc/plymouth/plymouthd.conf'
No state is present for card vc4hdmi0
alsa-lib main.c:1014:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
Found hardware: "vc4-hdmi" "" "" "" ""
Hardware is initialized using a generic method
No state is present for card vc4hdmi0
No state is present for card vc4hdmi1
alsa-lib main.c:1014:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -2
Found hardware: "vc4-hdmi" "" "" "" ""
Hardware is initialized using a generic method
No state is present for card vc4hdmi1
------------------------------------------------------
Please reboot your device to apply all settings
Enjoy!
```

**Comment by lakshanthad** [comment]
Hello @maziarzamani,

Could you please open `/boot/config.txt` file, delete the line **tp_rotate=1** and try again?

**Comment by bigbearishappy** [comment]
Hello, where did you get the system image, raspberrypi offcial or seeed wiki?

**Comment by maziarzamani** [comment]
> Hello @maziarzamani,
> 
> Could you please open `/boot/config.txt` file, delete the line **tp_rotate=1** and try again?

Hi @lakshanthad. Thanks for getting back to me! I just tried this workaround, and it fixed the touch display issue! Any idea why this is the case on 64-bit?

**Comment by maziarzamani** [comment]
> Hello, where did you get the system image, raspberrypi offcial or seeed wiki?

Hi @bigbearishappy. I did not find any 64-bit image on the seeed wiki, so I used the official in the Raspberry Pi flasher tool.

**Comment by maziarzamani** [comment]
> Hello @maziarzamani,
> 
> Could you please open `/boot/config.txt` file, delete the line **tp_rotate=1** and try again?

This fix solved the issue.
