### ISSUE TITLE
reTerminal DM Ubuntu support

### ISSUE THREAD

**Issue by kirwinrMK** [Seeed-Studio/seeed-linux-dtoverlays#63]
It seems the driver install method in `scripts/reTerminal.sh` don't support Ubuntu on the reTerminal DM. 
Is this a possibility to add?

**Comment by bigbearishappy** [comment]
We don't have a plan to support ubuntu on reTerminal DM. But we have did relative work on reTerminal.
You can take a look into [this](https://github.com/Seeed-Studio/seeed-linux-dtoverlays/issues/28#issuecomment-939662366).
It may help you to achieve what you want.

**Comment by danwalmsley** [comment]
In case anyone needs it, I have ubuntu 23.10 working on re terminal DM using these mods and --keep-kernel option.

https://github.com/danwalmsley/seeed-linux-dtoverlays/commit/edb961382bbeea31ce343b3d22336ba25734dbb7
