### ISSUE TITLE
Installation instructions suggestion for Raspberry Pi .

### ISSUE THREAD

**Issue by konkrer** [Seeed-Studio/seeed-linux-dtoverlays#70]
I needed to additionally run `make all_rpi` before the shown `sudo make install_rpi` command in the README.

Using only the `sudo make install_rpi` command as suggested raised errors.

Mentioning this setup command for RPI users could help prevent people from getting stuck.

---
On: reTerminal

**Comment by bigbearishappy** [comment]
Thank you for your suggestion. 
We have update the readme in this [commit](https://github.com/Seeed-Studio/seeed-linux-dtoverlays/commit/63b1498dc520b87ca00e2118191f91d7a6aa777a).
If you have any further suggestion about readme. Please reopen this issue or create a pull request.
