### ISSUE TITLE
[QUESTION]: Connecting Respeaker 6-Mic to Jetson Nano

### ISSUE THREAD

**Issue by Laura-VFA** [Seeed-Studio/seeed-linux-dtoverlays#74]
Hi there, I am trying to install the drivers to use a respeaker 6-mic array in a jetson nano, but it is not working. It is connected using the 40 pins.
I have tried to use these links:
https://wiki.seeedstudio.com/ReSpeaker_6-Mic_Circular_Array_kit_for_Raspberry_Pi/
https://wiki.seeedstudio.com/ReSpeaker_2_Mics_Pi_HAT_Jetson/

But it not seems to have support for the 6-mic array (although it has support for 2 and 4 mic respeakers). Is there any way to do this?

Thanks

**Comment by bigbearishappy** [comment]
Can you show us the details of the problem, just like error log?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
