### ISSUE TITLE
MCP2518FD - Jetson Orin Nano

### ISSUE THREAD

**Issue by julio981007** [Seeed-Studio/seeed-linux-dtoverlays#88]
Is there no Jetson Orin Nano version of the '/overlays/jetsonnano/2xMCP2518FD-spi0.dts' file? I want to use the MCP2518FD CAN shield with Jetson Orin Nano.

**Comment by is-qian** [comment]
Currently, we haven't tested the MCP2518 on the Jetson Orin Nano. You can attempt to make modifications based on /overlays/jetsonnano/2xMCP2518FD-spi0.dts to achieve integration. If you are able to run it stably, you can submit a PR to us for further testing. Now I will close this issue first.
