### ISSUE TITLE
[reTerminal DM] pwm-backlight: probe of lcd_backlight failed with error -22

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/seeed-linux-dtoverlays#94]
> from https://github.com/Seeed-Studio/seeed-linux-dtoverlays/issues/92#issuecomment-2005330129

Screen is not displayed.
It appears that there is an error in the backlight.

### dmesg

```
[    2.813589] OF: /lcd_backlight: #pwm-cells = 3 found 2
[    2.813630] of_pwm_get(): can't parse "pwms" property
[    2.813643] pwm-backlight lcd_backlight: unable to request PWM
[    2.813654] pwm-backlight: probe of lcd_backlight failed with error -22
```

**Comment by bigbearishappy** [comment]
@matsujirushi 
As you said in #92. We need to update the dts config of pwm for reTerminal DM.
Detail commit is [here](https://github.com/Seeed-Studio/seeed-linux-dtoverlays/commit/e4300f19eea0d81e7813762fb9fbeb2b5c4f868b).

And I test it with both bullseye and bookworm. All of them work fine.
