### ISSUE TITLE
Issue when running the command to install drivers

### ISSUE THREAD

**Issue by Dhoward094** [Seeed-Studio/seeed-linux-dtoverlays#99]
When trying to use the repo to have the respeaker 2 Mic be recognized with an Nvidia agx- orin I run into issues installing the drivers. I also made sure to follow the instructions here https://wiki.seeedstudio.com/ReSpeaker_2_Mics_Pi_HAT_Jetson/

When I run the:
 sudo -E KBUILD=/usr/src/linux-headers-5.10.120-tegra-ubuntu20.04_aarch64/kernel-5.10 make install_agx-orin
 
 I get the following error:
 cp: cannot stat 'agx-orin-seeed-reserver.dtbo-overlay.dtbo': No such file or directory
 
 from what it seems the installer is looking for the dtbo-overlay.dtbo for some reason, the file I find that is built is just agx-orin-seeed-reserver.dtbo so the installer may have an incorrect file name it is searching for. I looked through the code and found the script reTerminal and thought this may control the naming however I am still running into the same issue even after removing the -overlay.dtbo on line 394 and 395 from the reTerminal.sh file.

**Comment by is-qian** [comment]
This issue has been fixed in this [commit](https://github.com/Seeed-Studio/seeed-linux-dtoverlays/commit/062e5996592cccb6bdf223ec766689b71f8cbff2). You can pull the latest code and try again. If there are any problems, you can reopen this issue.
